<?php
$fontFamilyList = [
    'Agency FB',
    'Aharoni',
    'Alef',
    'Algerian',
    'Andalus',
    'Angsana New',
    'AngsanaUPC',
    'Aparajita',
    'Arabic Typesetting',
    'Arial',
    'Arial Black',
    'Arial Narrow',
    'Arial Unicode MS',
    'Baskerville Old Face',
    'Batang',
    'BatangChe',
    'Bauhaus 93',
    'Bell MT',
    'Berlin Sans FB',
    'Bernard MT Condensed',
    'Blackadder ITC',
    'Bodoni Bd BT',
    'Bodoni Bk BT',
    'Bodoni MT',
    'Bodoni MT Black',
    'Bodoni MT Condensed',
    'Book Antiqua',
    'Bookman Old Style',
    'Bookshelf Symbol 7',
    'Bradley Hand ITC',
    'Broadway',
    'Browallia New',
    'BrowalliaUPC',
    'Brush Script MT',
    'Calibri',
    'Calibri Light',
    'Californian FB',
    'Calisto MT',
    'Cambria',
    'Cambria Math',
    'Candara',
    'Castellar',
    'Centaur',
    'CentSchbkCyrill BT',
    'Century',
    'Century Gothic',
    'Century Schoolbook',
    'Century725 Cn BT',
    'Century751 BT',
    'Century751 No2 BT',
    'Century751 SeBd BT',
    'Chapenettoer 8 THIN',
    'Chiller',
    'Clarendon Blk BT',
    'Clarendon BT',
    'Clarendon Lt BT',
    'Colonna MT',
    'Comic Sans MS',
    'Consolas',
    'Constantia',
    'Cooper Black',
    'Copperplate Gothic Light',
    'Corbel',
    'Cordia New',
    'CordiaUPC',
    'Courier',
    'Courier New',
    'Curlz MT',
    'DaunPenh',
    'DeVinne Txt BT',
    'DFGothic-EB',
    'DFKai-SB',
    'DFMincho-SU',
    'DFMincho-UB',
    'DFPOP1-W9',
    'DilleniaUPC',
    'DokChampa',
    'Dotum',
    'DotumChe',
    'Ebrima',
    'Edwardian Script ITC',
    'Elephant',
    'Embassy BT',
    'Engravers MT',
    'EngraversGothic BT',
    'Estrangelo Edessa',
    'EucrosiaUPC',
    'Euphemia',
    'Exotc350 Bd BT',
    'Exotc350 DmBd BT',
    'FangSong',
    'Felix Titling',
    'Fixedsys Excelsior 3.01',
    'Footlight MT Light',
    'Forte',
    'Franklin Gothic Book',
    'Franklin Gothic Heavy',
    'Franklin Gothic Medium',
    'Freehand521 BT',
    'FreesiaUPC',
    'Freestyle Script',
    'French Script MT',
    'Futura Bk BT',
    'Futura Md BT',
    'Gabriola',
    'Garamond',
    'Gautami',
    'Geometr212 BkCn BT',
    'Geometr415 Blk BT',
    'Geometr706 BlkCn BT',
    'Georgia',
    'GeoSlab703 Md BT',
    'GeoSlab703 MdCn BT',
    'Gigi',
    'Gill Sans MT',
    'Gill Sans MT Condensed',
    'Gisha',
    'Goudy Old Style',
    'Goudy Stout',
    'Gulim',
    'GulimChe',
    'Gungsuh',
    'GungsuhChe',
    'Guttman Logo1',
    'Haettenschweiler',
    'Harrington',
    'High Tower Text',
    'Humanst521 BT',
    'Humanst521 Lt BT',
    'Humnst777 Blk BT',
    'Humnst777 BlkCn BT',
    'Humnst777 BT',
    'Humnst777 Cn BT',
    'Humnst777 Lt BT',
    'Impact',
    'Imprint MT Shadow',
    'Informal Roman',
    'IrisUPC',
    'Japanese',
    'JasmineUPC',
    'Jokerman',
    'Juice ITC',
    'KaiTi',
    'Kalinga',
    'Kartika',
    'Kaufmann BT',
    'Khmer UI',
    'KodchiangUPC',
    'Kokila',
    'Kristen ITC',
    'Kunstler Script',
    'Lao UI',
    'Latha',
    'Leelawadee',
    'Levenim MT',
    'LilyUPC',
    'Liron',
    'Lithos Pro Light',
    'Lucida Bright',
    'Lucida Calligraphy',
    'Lucida Console',
    'Lucida Fax',
    'Lucida Handwriting',
    'Lucida Sans',
    'Lucida Sans Typewriter',
    'Lucida Sans Unicode',
    'LuzSans-Book',
    'Magneto',
    'Maiandra GD',
    'Malgun Gothic',
    'Mangal',
    'Matura MT Script Capitals',
    'Meiryo',
    'Meiryo UI',
    'Microsoft Himalaya',
    'Microsoft JhengHei',
    'Microsoft New Tai Lue',
    'Microsoft PhagsPa',
    'Microsoft Sans Serif',
    'Microsoft Tai Le',
    'Microsoft Uighur',
    'Microsoft YaHei',
    'Microsoft Yi Baiti',
    'MingLiU',
    'MingLiU-ExtB',
    'MingLiU_HKSCS',
    'MingLiU_HKSCS-ExtB',
    'Miriam',
    'Miriam Fixed',
    'Mistral',
    'Modern No. 20',
    'Monotype Corsiva',
    'Monotype Hadassah',
    'MoolBoran',
    'MS Gothic',
    'MS Mincho',
    'MS PGothic',
    'MS PMincho',
    'MS Reference Sans Serif',
    'MS Reference Specialty',
    'MS Sans Serif',
    'MS UI Gothic',
    'MV Boli',
    'Myriad Pro',
    'Myriad Pro Light',
    'Narkisim',
    'News701 BT',
    'News706 BT',
    'NewsGoth BT',
    'NewsGoth Cn BT',
    'NewsGoth Lt BT',
    'Niagara Engraved',
    'Niagara Solid',
    'NSimSun',
    'Nyala',
    'OCR-A BT',
    'OCR-B 10 BT',
    'Old English Text MT',
    'Onyx',
    'Palace Script MT',
    'Palatino Linotype',
    'Papyrus',
    'Parchment',
    'Perpetua',
    'Perpetua Titling MT',
    'Plantagenet Cherokee',
    'Playbill',
    'PMingLiU',
    'PMingLiU-ExtB',
    'Poor Richard',
    'Pristina',
    'Raavi',
    'Ravie',
    'Rockwell',
    'Rockwell Condensed',
    'Rod',
    'Sakkal Majalla',
    'Schadow BT',
    'Segoe Print',
    'Segoe Script',
    'Segoe UI',
    'Segoe UI Light',
    'Segoe UI Semibold',
    'Segoe UI Symbol',
    'Shonar Bangla',
    'Showcard Gothic',
    'Shruti',
    'SimHei',
    'Simplified Arabic',
    'Simplified Arabic Fixed',
    'SimSun',
    'SimSun-ExtB',
    'Snap ITC',
    'Square721 BT',
    'Square721 Cn BT',
    'Stencil',
    'Swis721 Blk BT',
    'Swis721 BlkCn BT',
    'Swis721 BT',
    'Swis721 Cn BT',
    'Swis721 Hv BT',
    'Swis721 Lt BT',
    'Swis721 LtEx BT',
    'Swis721 WGL4 BT',
    'Sylfaen',
    'Symbol',
    'Tahoma',
    'Tamir',
    'Tempus Sans ITC',
    'Times New Roman',
    'Traditional Arabic',
    'Trebuchet MS',
    'Tunga',
    'Tw Cen MT',
    'Tw Cen MT Condensed',
    'TypoUpright BT',
    'Utsaah',
    'Vani',
    'Verdana',
    'Vijaya',
    'Viner Hand ITC',
    'Vivaldi',
    'Vladimir Script',
    'Vrinda',
    'Webdings',
    'Wide Latin',
    'Wingdings',
    'Wingdings 2',
    'Wingdings 3',
    'WP Arabic Sihafa',
    'WP ArabicScript Sihafa',
    'WP CyrillicA',
    'WP Greek Century',
    'WP Greek Courier',
    'WP Greek Helve',
    'WP Hebrew David',
    'WP MultinationalA Courier',
    'WP MultinationalA Helve',
    'WP MultinationalA Roman',
    'WP MultinationalB Courier',
    'ＤＦ中太楷書体',
    'ＤＦ明朝体W5',
];
?>
<?php
foreach ($fontFamilyList as $fontFamily) {
    echo '<li data-value="' . $fontFamily . '"  style="font-family: \'' . $fontFamily . '\'">' . $fontFamily . '</li>';
}
?>